---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops