- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: httpd-dev
        path: components/dependencies/httpd-server/overlays/default
        namespace: kubevirt-gitops
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: datavolumes-dev
        path: components/vm-workloads/datavolumes/overlays/openshift
        namespace: kubevirt-gitops
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: vms-dev
        path: components/vm-workloads/vms/overlays/openshift
        namespace: kubevirt-gitops
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: win2k19-dev
        path: components/vm-workloads/win2k19/overlays/openshift
        namespace: kubevirt-gitops
