- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: win2k19
        path: components/vm-workloads/win2k19/overlays/openshift
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: datavolumes
        path: components/vm-workloads/datavolumes/overlays/openshift
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: vms
        path: components/vm-workloads/vms/overlays/openshift