apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavolumes
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: openshift-virtualization-os-images
  project: default
  source:
    path: datavolumes/overlays/openshift
