apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: virtualization
    repoURL: https://github.com/tosin2013/kubevirt-gitops.git
    targetRevision: rosa
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - kind: HyperConverged
    namespace: openshift-cnv
    jsonPointers:
    - /spec/version
