---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vms-cdi-view
  namespace: kubevirt-os-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi.kubevirt.io:view
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubevirt-gitops
