- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://api.ocp4.example.com:6443
      values:
        name: httpd-prod
        path: components/dependencies/httpd-server/overlays/default
        namespace: kubevirt-gitops
    - cluster: local
      url: https://api.ocp4.example.com:6443
      values:
        name: datavolumes-prod
        path: components/vm-workloads/datavolumes/overlays/openshift
        namespace: kubevirt-gitops
    - cluster: local
      url: https://api.ocp4.example.com:6443
      values:
        name: vms-prod
        path: components/vm-workloads/vms/overlays/openshift
        namespace: kubevirt-gitops
    - cluster: local
      url: https://api.ocp4.example.com:6443
      values:
        name: win2k19-prod
        path: components/vm-workloads/win2k19/overlays/openshift
        namespace: kubevirt-gitops
