apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavolumes
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: kubevirt-os-images
    server: https://kubernetes.default.svc
  project: default
  source:
    path: datavolumes/overlays/kubernetes
    repoURL: https://github.com/tosin2013/kubevirt-gitops.git
    targetRevision: rosa
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
