apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: win2k19
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    path: win2k19/overlays/kubernetes
    repoURL: https://github.com/tosin2013/kubevirt-gitops.git
    targetRevision: rosa
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
