apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    deployOVS: "false"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: kubevirt-hyperconverged
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  featureGates:
    deployTektonTaskResources: false
    enableCommonBootImageImport: true
    withHostPassthroughCPU: false
    disableMDevConfiguration: false
    deployKubeSecondaryDNS: false
    nonRoot: true
    enableManagedTenantQuota: false
    deployVmConsoleProxy: false
    persistentReservation: false
  infra: {}
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  workloads: {}
