---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-virtualization-os-images
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-gitops
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
